In [1]:
import pandas as pd

In [2]:

df1 = pd.DataFrame({'Name':['Anu','Ram']})
df2 = pd.DataFrame({'Name':['Priya','Kiran']})

pd.concat([df1, df2])

    Name
0    Anu
1    Ram
0  Priya
1  Kiran

In [13]:
employees = pd.DataFrame({
    'id':[1,2,3],
    'name':['Anu','Ram','Priya']
})

salaries = pd.DataFrame({
    'id':[2,3,4],
    'salary':[50000,60000,70000]
})

pd.merge(employees, salaries, on='id')

   id   name  salary
0   2    Ram   50000
1   3  Priya   60000

In [14]:
pd.merge(employees, salaries, on='id', how='left')

   id   name   salary
0   1    Anu      NaN
1   2    Ram  50000.0
2   3  Priya  60000.0

In [15]:
pd.merge(employees, salaries, on='id', how='right')

   id   name  salary
0   2    Ram   50000
1   3  Priya   60000
2   4    NaN   70000

In [16]:
pd.merge(employees, salaries, on='id', how='inner')

   id   name  salary
0   2    Ram   50000
1   3  Priya   60000

In [17]:
pd.merge(employees, salaries, on='id', how='outer')

   id   name   salary
0   1    Anu      NaN
1   2    Ram  50000.0
2   3  Priya  60000.0
3   4    NaN  70000.0