In [5]:
import pandas as pd

In [11]:
df = pd.read_csv(
    "/workspaces/ai-engineer-journey/data/survey_results_public.csv",
    engine="python",
    on_bad_lines="skip",
    index_col="ResponseId"
)
schema_df = pd.read_csv("/workspaces/ai-engineer-journey/data/survey_results_schema.csv", index_col="qname")

In [12]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [13]:
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,...,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,...,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,...,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,...,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,...,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,...,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [14]:
high_salary = (df['ConvertedCompYearly'] > 70000)

In [16]:
df.loc[high_salary, ['AIAgentExternal', 'ConvertedCompYearly', 'WorkExp']]

                          AIAgentExternal  ConvertedCompYearly  WorkExp
ResponseId
2                                     NaN             104413.0      2.0
6                          GitHub Copilot             120000.0     15.0
8                                     NaN              72000.0     22.0
23                                    NaN              87500.0      7.0
26          ChatGPT;GitHub Copilot;Replit             108913.0     37.0
...                                   ...                  ...      ...
35978                                 NaN              74423.0     29.0
35981                                 NaN             130008.0     10.0
35987                                 NaN             155521.0     41.0
36017                                 NaN              87763.0      6.0
36023                                 NaN              78890.0      5.0

[9856 rows x 3 columns]

In [8]:
filt = df['AIAgentExternal'].str.contains('ChatGPT', na=False)

In [9]:
filt

ResponseId
1         True
2        False
3         True
4         True
5        False
         ...
36019    False
36020    False
36021    False
36022     True
36023    False
Name: AIAgentExternal, Length: 36022, dtype: bool

In [10]:
df.loc[filt]

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,...,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,...,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,...,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,...,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,13.0,"Developer, full-stack",NaN,NaN,NaN,No,Personal Project,11.0,1.0,2.0,6.0,4.0,7.0,13.0,8.0,3.0,14.0,NaN,8.0,3.0,14.0,11.0,4.0,1.0,10.0,5.0,13.0,15.0,NaN,Insurance,4.0,6.0,...,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,NaN,Project planning;Debugging or fixing code;Comm...,NaN,NaN,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work monthly or infreq...","Yes, somewhat",Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,NaN,NaN,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,Sentry,NaN,ChatGPT;Claude Code;Google Gemini,NaN,When I don’t trust AI’s answers;When I need he...,NaN,6240.0,6.0
11,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,9.0,"Developer, back-end",100 to 499 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a tool that ...",Work,11.0,4.0,5.0,13.0,7.0,8.0,2.0,3.0,10.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fintech,6.0,7.0,...,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools daily",Very favorable,Somewhat distrust,Very poor at handling complex tasks,Learning about a codebase;Project planning;Wri...,Debugging or fixing code;Testing code;Deployme...,NaN,NaN,Search for answers;Generating content or synth...,"AI solutions that are almost right, but not qu...",When I need to prototype something then yes it...,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering,NaN,AI agents have helped me automate repetitive t...,AI agents have improved the quality of my code...,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,It takes significant time and effort to learn ...,NaN,NaN,NaN,Spring AI,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Microsoft C...,NaN,When I don’t trust AI’s answers;When I have et...,Code writing. I know this sounds weird but you...,65691.0,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36001,I am a developer by profession,35-44 years old,Some college/university study without earning ...,Employed,None of the above,11.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Other (please specify):,13.0,"Developer, back-end",Less than 20 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Work,8.0,7.0,1.0,3.0,2.0,5.0,9.0,6.0,4.0,10.0,NaN,9.0,8.0,2.0,6.0,4.0,1.0,5.0,3.0,7.0,10.0,NaN,Software Development,7.0,4.0,...,9.0,10.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools weekly",Unsure,Highly distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Debuggi...,Project planning;Testing code;Committing and r...,Documenting code;Creating or maintaining docum...,NaN,NaN,"AI solutions that are almost right, but not qu...","No, I've tried it but it's nowhere close to be...","Yes, I use AI agents at work weekly",Not at all or minimally,Software engineering;Data and analytics,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me solve complex problem...,NaN,AI agents have helped me automate repetitive t...,AI agents have improved the quality of my code.,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,I have concerns about the security and privacy...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;Perplexity,ReSharper AI Assistant (Mellum),When I don’t trust AI’s answers;When I want to...,"Understanding of code quality, what trade-offs...",65409.0,8.0
36005,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc....",35.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,40.0,"Developer, embedded applications or devices","10,000 or more employees",Individual contributor,Remote,"Yes, I influenced the purchase of a substantia...",Work,2.0,1.0,4.0,6.0,3.0,9.0,8.0,5.0,7.0,10.0,NaN,7.0,3.0,8.0,6.0,2.0,4.0,1.0,9.0,5.0,10.0,NaN,Manufacturing,7.0,1.0,...,8.0,10.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Favorable,Somewhat trust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,NaN,Project planning;Deployment and monitoring,NaN,Documenting code;Search for answers;Generating...,"AI solutions that are almost right, but not quite",NaN,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering,Multi-platform search enablement;Language proc...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,My company's IT and/or InfoSec teams have stri...,GitHub MCP Server;mem0,NaN,CrewAI;IBM watsonx.ai;Llama Index,NaN,Sentry;Protect AI,NaN,ChatGPT;GitHub Copilot;Google Gemini;Microsoft...,NaN,When I don’t trust AI’s answers;When I want to...,Nothing will change compared to what is now,NaN,8.0
36014,I am learning to code,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Attending school (part-time),10.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...","Other online resources (e.g. standard search, ...",1.0,Other (please specify):,Less than 20 employees,Individual contributor,In-person,No,Work,1.0,7.0,9.0,4.0,5.0,8.0,6.0,3.0,2.0,10.0,NaN,7.0,2.0,6.0,5.0,1.0,3.0,9.0,4.0,8.0,10.0,NaN,Higher Education,NaN,NaN,...,5.0,10.0,NaN,"Yes, somewhat",Less than half of the time,"Yes, I use AI tools daily",Favorable,Neither trust nor distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,NaN,Documenting code;Deployment and monitoring;Pre...,Creating or maintaining documentation,NaN,"AI solutions that are almost right, but not quite",No.,"Yes, I use AI agents at work daily","Yes, to a great extent",Software engineering,Multi-platform search enablement;Language proc...,AI agents have improved the quality of my code...,AI agents have helped me automate repetitive t...,AI agents have improved collaboration within m...,AI agents have increased my productivity.;AI a...,NaN,My company's IT and/or InfoSec teams have stri...,Integrating AI agents with my existing tools a...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemi...,NaN,When I don’t trust AI’s answers;When I have et...,human creativity coming from real-life experie...,NaN,NaN
36016,I am a developer by profession,45-54 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",12.0,"Yes, I am new to coding or currently a student",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Other (please specify):,15.0,"Developer, full-stack","10,000 or more employees",Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Work,9.0,2.0,6.0,5.0,1.0,3.0,7.0,4.0,8.0,10.0,NaN,9.0,2.0,8.0,7.0,6.0,1.0,3.0,5.0,4.0,10.0,NaN,Government,4.0,2.0,...,9.0,10.0,NaN,"Yes, somewhat","Rarely, almost never","Yes, I use AI tools daily",Unsure,Somewhat distrust,Very poor at handling complex tasks,NaN,Project planning;Writing code;Testing code;Dep...,Learning about a codebase;Documenting code;Deb...,NaN,NaN,Other (write in):,Somewhat to get an initial grasp of some conce...,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering,NaN,AI agents have increased my productivity.;AI a...,NaN,NaN,AI agents have accelerated my learning about n...,AI agents have helped me automate repetitive t...,NaN,It takes significant time and effort to learn ...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,Ollama,NaN,NaN,NaN,ChatGPT;GitHub Copilot,NaN,When I don’t trust AI’s answers;When I want to...,"Tools will be interchangeable/replaceable, but...",52207.0,4.0
36022,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Online Courses or Certification (includes all ...,12.0,"Developer, full-stack","10,000 or more employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a tool that ...",Work,6.0,2.0,4.0,5.0,7.0,8.0,9.0,3.0,1.0,10.0,NaN,9.0,7.0,6.0,3.0,4.0,2.0,5.0,8.0,1.0,10.0,NaN,Manufacturing,3.0,4.0,...,5.0,10.0,NaN,"Yes, definitely",Less than half of the time,"Yes, I use AI tools daily",Very favorable,Highly distrust,Very poor at handling complex tasks,Learning about a codebase;Debugging or fixing ...,Project planning;Documenting code;Committing a...,Writing code,Testing code;Deployment and monitoring;Search ...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,AI agents have improved the quality of my code.,AI agents have helped me solve complex problem...,AI agents have reduced the time spent on speci...,NaN,NaN,The cost of using certain AI agent platforms i...,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot,NaN,When I don’t trust AI’s answers;When I have et...,Full Stack Web Development - developer which u...,NaN,6.0